import requests
import json

STORAGE_URL = "http://127.0.0.1:5000/api/storage/v2/records"
HEADERS = {"Content-Type": "application/json", "data-partition-id": "opendes"}

if __name__ == "__main__":
    with open("autogenerated.json", "r", encoding="utf-8") as f:
        payload = json.load(f)

    resp = requests.put(STORAGE_URL, headers=HEADERS, data=json.dumps(payload))
    print("Status Code:", resp.status_code)
    try:
        print("Response JSON:", json.dumps(resp.json(), indent=2))
    except Exception:
        print("Response Text:", resp.text)
